// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkA36g61xQoOy17f_uO74dAuGLTsHc3ls',
    appId: '1:605067043767:web:572fae72ff2b24eab83e32',
    messagingSenderId: '605067043767',
    projectId: 'video-app-24be0',
    authDomain: 'video-app-24be0.firebaseapp.com',
    storageBucket: 'video-app-24be0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWBfk1MOgmQodts3_ctNtvGrdeqzcHr3o',
    appId: '1:605067043767:android:e1616833da0e00c0b83e32',
    messagingSenderId: '605067043767',
    projectId: 'video-app-24be0',
    storageBucket: 'video-app-24be0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApctqqqQXKJso4FTBJtvfa7iM6ejnWnWo',
    appId: '1:605067043767:ios:29589e8aa8fd8053b83e32',
    messagingSenderId: '605067043767',
    projectId: 'video-app-24be0',
    storageBucket: 'video-app-24be0.appspot.com',
    iosClientId: '605067043767-n9n5pqqe0kcpthjpe4loei1ri7nia2jv.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApctqqqQXKJso4FTBJtvfa7iM6ejnWnWo',
    appId: '1:605067043767:ios:fd9d8a6bc16a7d66b83e32',
    messagingSenderId: '605067043767',
    projectId: 'video-app-24be0',
    storageBucket: 'video-app-24be0.appspot.com',
    iosClientId: '605067043767-nndflfutgco61si21p1vi6qrb64v7dlj.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase1.RunnerTests',
  );
}
